### PR TITLE
`additionalProperties` + `enum`s

### PR DESCRIPTION
**Pull request by hudson-ai**
Hey @riedgar-ms, I ported my implementations of `additionalProperties` and `enum` to the rewrite. 

I don't want to cause a delay to #651 being merged, so feel free to ignore this, and I'll be happy to submit this as a standalone PR to the main repo once the rewrite is merged. Just wanted this to be on your radar!

### CODE REVIEW

**Comment by hudson-ai** [comment]
TODO: array [prefixItems](https://json-schema.org/understanding-json-schema/reference/array#tupleValidation)

**Comment by riedgar-ms** [comment]
Thanks for working on this - I'm aware that my implementation of the JSON schema was minimal. I'd tend towards letting my PR go through, and having this as a separate one, but we can see what Scott says on that.

**Comment by hudson-ai** [comment]
I'm in full agreement. I want your PR merged as soon as possible!

**Comment by riedgar-ms** [comment]
@hudson-ai My changes have been merged, if you want to make this a PR against the main repo

**Comment by hudson-ai** [comment]
@riedgar-ms awesome, great work! I'll rebase and submit a PR when I find some time :)

**Comment by hudson-ai** [comment]
It was quicker than I expected. PR: https://github.com/guidance-ai/guidance/pull/685

**Pull request closed without merging**
